### ISSUE TITLE
Configure Git in the PHP Container

### ISSUE THREAD

**Issue by jfcodiaz** [jfcodiaz/my-vocabulary-api#10]
# Configure Git in the PHP Container

### Tasks
- [x] Mount the entire project into the PHP container at `/app`  
  **20 - 30 mins**

- [x] Mount the Git configuration files (SSH key)  
  **15 - 25 mins**

- [x] Add the SSH key to the `.gitignore` file  
  **5 - 10 mins**

- [x] Ensure Git can be used inside the container  
  **10 - 15 mins**

---

### Total Estimated Time:
**50 - 80 mins**

**Comment by jfcodiaz** [comment]
Started working on it

**Comment by jfcodiaz** [comment]
Finished working on: Mount the entire project into the PHP container at /app

**Comment by jfcodiaz** [comment]
Started working on: Mount the Git configuration files (SSH key)

**Comment by jfcodiaz** [comment]
Fninish 80min

Extra Task

- Install vi in the PHP container
- Install Locales UTF-8 to display correctly emojics
