### ISSUE TITLE
List Conjugation Types

### ISSUE THREAD

**Issue by jfcodiaz** [jfcodiaz/my-vocabulary-api#12]
### Tasks
- [x]  Map model `ConjugationType`  
  **20 - 30 mins**

- [x] Create the endpoint `api/v1/conjugation_types`  
  List all conjugation types without pagination  
  **30 - 45 mins**

- [x]  Create test  `api/v1/conjugation_types`  
  **30 - 45 mins**

- [x]  Add endpoint and test in Postman  
  **15 - 25 mins**

- [x] Configure Swagger  
  **20 - 30 mins**

- [x] Document endpoint  
  **15 - 20 mins**

---

### Total Estimated Time:
**120 - 195 mins**
