### ISSUE TITLE
List Word Types

### ISSUE THREAD

**Issue by jfcodiaz** [jfcodiaz/my-vocabulary-api#14]
### Tasks
- [x] Map model `WordType`  
  **20 - 30 mins**

- [x] Create the endpoint `api/v1/word_types`  
  List all word types without pagination  
  **30 - 45 mins**

- [x] Create test  
  **30 - 45 mins**

- [x] Add endpoint and test in Postman  
  **15 - 25 mins**

- [x] Document endpoint  
  **15 - 20 mins**

---

### Total Estimated Time:
**105 - 165 mins**
