### ISSUE TITLE
Configure Tests, LinterTest, and SonarCloud on GitHub Actions

### ISSUE THREAD

**Issue by jfcodiaz** [jfcodiaz/my-vocabulary-api#16]
### Tasks
- [x] Configure GitHub Actions to run unit tests  
  **30 - 45 mins**

- [x] Configure GitHub Actions to run LinterTest (PHPCS)  
  **30 - 45 mins**

- [x] Configure GitHub Actions to run SonarCloud analysis  
  **30 - 45 mins**

---

### Total Estimated Time:
**90 - 135 mins**

**Comment by jfcodiaz** [comment]
SonarCoud take more time (15hrs), considerate for next the time for test and fix the initial issues, review token GIT/SONARCLOUD, proyect names
